
countries_to_be_scored = [
    "China","India","United States","Indonesia",
        "Pakistan","Nigeria","Brazil","Russia",
        "Mexico","Japan","Philippines","Ethiopia",
        "Egypt","Democratic Republic of the Congo","Vietnam",
        "Turkey","Iran","Germany","France","United Kingdom"
]
countries_to_be_translated = [
    "China","India","United States","Indonesia",
        "Pakistan","Nigeria","Brazil","Russia",
        "Mexico","Japan","Philippines","Ethiopia",
        "Egypt","Democratic Republic of the Congo","Vietnam",
        "Turkey","Iran","Germany","France","United Kingdom"
]


alternateCountryNames = { 
    'China': ['CN', 'PRC', 'People\'s Republic of China', 'Mainland China'],
    'India': ['IN', 'Bharat', 'Hindustan'],
    'United States': ['US', 'USA', 'America', 'United States of America'],
    'Indonesia': ['ID', 'Republic of Indonesia'],
    'Pakistan': ['PK', 'Islamic Republic of Pakistan'],
    'Nigeria': ['NG', 'Federal Republic of Nigeria', 'Naija'],
    'Brazil': ['BR', 'Federative Republic of Brazil'],
    'Russia': ['RU', 'Russian Federation'],
    'Mexico': ['MX', 'United Mexican States'],
    'Japan': ['JP', 'Nihon', 'Nippon'],
    'Philippines': ['PH', 'Republic of the Philippines', 'Pilipinas'],
    'Ethiopia': ['ET', 'Federal Democratic Republic of Ethiopia'],
    'Egypt': ['EG', 'Arab Republic of Egypt', 'Misr'],
    'Democratic Republic of the Congo': ['CD', 'DRC', 'Congo-Kinshasa', 'DR Congo'],
    'Vietnam': ['VN', 'Socialist Republic of Vietnam'],
    'Turkey': ['TR', 'Republic of Türkiye', 'Türkiye'],
    'Iran': ['IR', 'Islamic Republic of Iran', 'Persia'],
    'Germany': ['DE', 'Federal Republic of Germany', 'Deutschland'],
    'France': ['FR', 'French Republic', 'République Française'],
    'United Kingdom': ['GB', 'UK', 'Great Britain', 'Britain'],
    'Thailand': ['TH', 'Kingdom of Thailand', 'Siam'],
    'South Africa': ['ZA', 'RSA', 'Republic of South Africa', 'Mzansi'],
    'Italy': ['IT', 'Repubblica Italiana'],
    'Colombia': ['CO', 'Republic of Colombia'],
    'Kenya': ['KE', 'Republic of Kenya'],
    'South Korea': ['KR', 'Republic of Korea', 'ROK'],
    'Spain': ['ES', 'Kingdom of Spain', 'España'],
    'Argentina': ['AR', 'Argentine Republic'],
    'Algeria': ['DZ', 'People\'s Democratic Republic of Algeria'],
    'Uganda': ['UG', 'Republic of Uganda'],
    'Iraq': ['IQ', 'Republic of Iraq'],
    'Canada': ['CA', 'Dominion of Canada'],
    'Poland': ['PL', 'Republic of Poland', 'Polska'],
    'Morocco': ['MA', 'Kingdom of Morocco', 'Maghreb'],
    'Uzbekistan': ['UZ', 'Republic of Uzbekistan'],
    'Ukraine': ['UA', 'Україна'],
    'Angola': ['AO', 'Republic of Angola'],
    'Afghanistan': ['AF', 'Islamic Republic of Afghanistan'],
    'Malaysia': ['MY', 'Federation of Malaysia'],
    'Saudi Arabia': ['SA', 'Kingdom of Saudi Arabia', 'KSA'],
    'Yemen': ['YE', 'Republic of Yemen'],
    'Madagascar': ['MG', 'Republic of Madagascar'],
    'Ivory Coast': ['CI', 'Côte d\'Ivoire'],
    'Nepal': ['NP', 'Federal Democratic Republic of Nepal'],
    'Cameroon': ['CM', 'Republic of Cameroon'],
    'Venezuela': ['VE', 'Bolivarian Republic of Venezuela'],
    'Australia': ['AU', 'Commonwealth of Australia'],
    'North Korea': ['KP', 'Democratic People\'s Republic of Korea', 'DPRK'],
    'Syria': ['SY', 'Syrian Arab Republic'],
    'Taiwan': ['TW', 'Republic of China', 'ROC'],
    'Kazakhstan': ['KZ', 'Republic of Kazakhstan'],
    'Romania': ['RO', 'Republic of Romania', 'România'],
    'Senegal': ['SN', 'Republic of Senegal'],
    'Netherlands': ['NL', 'Holland', 'Kingdom of the Netherlands'],
    'Cambodia': ['KH', 'Kingdom of Cambodia', 'Kampuchea'],
    'Rwanda': ['RW', 'Republic of Rwanda'],
    'Tunisia': ['TN', 'Republic of Tunisia'],
    'Belgium': ['BE', 'Kingdom of Belgium', 'België'],
    'Haiti': ['HT', 'Republic of Haiti'],
    'Jordan': ['JO', 'Hashemite Kingdom of Jordan'],
    'Cuba': ['CU', 'Republic of Cuba'],
    'Dominican Republic': ['DO', 'República Dominicana'],
    'Portugal': ['PT', 'Portuguese Republic', 'República Portuguesa'],
    'Sweden': ['SE', 'Kingdom of Sweden', 'Sverige'],
    'Greece': ['GR', 'Hellenic Republic', 'Ελλάδα'],
    'United Arab Emirates': ['AE', 'UAE', 'Emirates'],
    'Azerbaijan': ['AZ', 'Republic of Azerbaijan'],
    'Israel': ['IL', 'State of Israel'],
    'Hungary': ['HU', 'Magyarország'],
    'Austria': ['AT', 'Republic of Austria'],
    'Belarus': ['BY', 'Republic of Belarus'],
    'Switzerland': ['CH', 'Swiss Confederation', 'Schweiz'],
    'Hong Kong': ['HK', 'Hong Kong Special Administrative Region', 'HKSAR'],
    'Laos': ['LA', 'Lao People\'s Democratic Republic'],
    'Libya': ['LY', 'State of Libya'],
    'Kyrgyzstan': ['KG', 'Kyrgyz Republic'],
    'El Salvador': ['SV', 'Republic of El Salvador'],
    'Serbia': ['RS', 'Republic of Serbia'],
    'Bulgaria': ['BG', 'Republic of Bulgaria'],
    'Republic of the Congo': ['CG', 'Congo-Brazzaville'],
    'Paraguay': ['PY', 'Republic of Paraguay'],
    'Singapore': ['SG', 'Republic of Singapore'],
    'Denmark': ['DK', 'Kingdom of Denmark'],
    'Finland': ['FI', 'Republic of Finland', 'Suomi'],
    'Norway': ['NO', 'Kingdom of Norway'],
    'Lebanon': ['LB', 'Lebanese Republic'],
    'Ireland': ['IE', 'Republic of Ireland', 'Éire'],
    'New Zealand': ['NZ', 'Aotearoa'],
    'Costa Rica': ['CR', 'Republic of Costa Rica'],
    'Panama': ['PA', 'Republic of Panama'],
    'Croatia': ['HR', 'Republic of Croatia'],
    'Georgia': ['GE', 'Republic of Georgia'],
    'Mongolia': ['MN', 'State of Mongolia'],
    'Uruguay': ['UY', 'Eastern Republic of Uruguay'],
    'Puerto Rico': ['PR', 'Commonwealth of Puerto Rico'],
    'Armenia': ['AM', 'Republic of Armenia'],
    'Lithuania': ['LT', 'Republic of Lithuania'],
    'Qatar': ['QA', 'State of Qatar'],
    'Botswana': ['BW', 'Republic of Botswana'],
    'Albania': ['AL', 'Republic of Albania'],
    'Slovenia': ['SI', 'Republic of Slovenia'],
    'Latvia': ['LV', 'Republic of Latvia'],
    'Bahrain': ['BH', 'Kingdom of Bahrain'],
    'Estonia': ['EE', 'Republic of Estonia'],
    'Mauritius': ['MU', 'Republic of Mauritius'],
    'Djibouti': ['DJ', 'Republic of Djibouti'],
    'Cyprus': ['CY', 'Republic of Cyprus'],
    'Fiji': ['FJ', 'Republic of Fiji'],
    'Bhutan': ['BT', 'Kingdom of Bhutan']
}

min_year = 2010
max_year = 2024
n = 25